import {EVENT_TYPE_TAGS} from "./tags";
import {MAX_DESCRIPTION_LENGTH} from "./sizes";
import {MONTH_NAMES_RU, MONTH_NAMES_SHORT_RU, DAYS_NAMES_RU, DAYS_NAMES_SHORT_RU, TODAY_RU} from "./datesNaming";

export {
    EVENT_TYPE_TAGS,
    MAX_DESCRIPTION_LENGTH,
    MONTH_NAMES_RU,
    MONTH_NAMES_SHORT_RU,
    DAYS_NAMES_RU,
    DAYS_NAMES_SHORT_RU,
    TODAY_RU
}